# -*- coding: utf-8 -*-
"""Expansión nacional de la red.html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWf-9kh5ej1H36hJLrF4uhqsJ3mbSCNe
"""

# --- Expansión nacional de la red (2000–2026) ---
# Script listo para copiar y pegar en Google Colab

import pandas as pd
import altair as alt

# Cargar la base real
df = pd.read_excel('BASE DE DATOS Cánepa.xlsx', sheet_name='regiones')

# Seleccionar columnas relevantes
df = df[['estaciones', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
         '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
         '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026']]

# Transformar a formato largo
df_long = df.melt(id_vars='estaciones', var_name='Año', value_name='PM25')
df_long['Año'] = df_long['Año'].astype(int)

# Contar cuántas estaciones tienen datos por año (expansión de la red)
expansion = df_long.groupby('Año')['estaciones'].nunique().reset_index()
expansion.rename(columns={'estaciones': 'Estaciones_activas'}, inplace=True)

# Crear gráfico Altair
chart = alt.Chart(expansion).mark_bar(color='#4A90E2').encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Estaciones_activas:Q', title='Número de estaciones activas'),
    tooltip=['Año', 'Estaciones_activas']
).properties(
    title='Expansión nacional de la red de monitoreo (2000–2026)',
    width=700,
    height=400
)

# Exportar en HTML interactivo
chart.save('expansion_nacional.html')

print("✅ Gráfico generado correctamente: expansion_nacional.html")

# --- Expansión nacional de la red (2000–2026) ---
# Script listo para Google Colab con subida de archivo

import pandas as pd
import altair as alt
from google.colab import files

# 1. Subir el archivo desde tu computador
# Ejecuta esta celda y selecciona "BASE DE DATOS Cánepa.xlsx"
uploaded = files.upload()

# 2. Cargar la base real
df = pd.read_excel('BASE DE DATOS Cánepa.xlsx', sheet_name='regiones')

# 3. Seleccionar columnas relevantes
df = df[['estaciones', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
         '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
         '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026']]

# 4. Transformar a formato largo
df_long = df.melt(id_vars='estaciones', var_name='Año', value_name='PM25')
df_long['Año'] = df_long['Año'].astype(int)

# 5. Contar cuántas estaciones tienen datos por año (expansión de la red)
expansion = df_long.groupby('Año')['estaciones'].nunique().reset_index()
expansion.rename(columns={'estaciones': 'Estaciones_activas'}, inplace=True)

# 6. Crear gráfico Altair
chart = alt.Chart(expansion).mark_bar(color='#4A90E2').encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Estaciones_activas:Q', title='Número de estaciones activas'),
    tooltip=['Año', 'Estaciones_activas']
).properties(
    title='Expansión nacional de la red de monitoreo (2000–2026)',
    width=700,
    height=400
)

# 7. Exportar en HTML interactivo
chart.save('expansion_nacional.html')

print("✅ Gráfico generado correctamente: expansion_nacional.html")

# --- Expansión nacional de la red (2000–2026) ---
# Script listo para Google Colab con subida de archivo

import pandas as pd
import altair as alt
from google.colab import files

# 1. Subir el archivo desde tu computador
# Ejecuta esta celda y selecciona "BASE DE DATOS Cánepa.xlsx"
uploaded = files.upload()

# 2. Verifica el nombre del archivo subido
# Colab suele renombrar con "(1)" si ya existía otro archivo
filename = list(uploaded.keys())[0]
print("Archivo cargado:", filename)

# 3. Cargar la base real
df = pd.read_excel(filename, sheet_name='regiones')

# 4. Seleccionar columnas relevantes
df = df[['estaciones', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
         '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
         '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026']]

# 5. Transformar a formato largo
df_long = df.melt(id_vars='estaciones', var_name='Año', value_name='PM25')
df_long['Año'] = df_long['Año'].astype(int)

# 6. Contar cuántas estaciones tienen datos por año (expansión de la red)
expansion = df_long.groupby('Año')['estaciones'].nunique().reset_index()
expansion.rename(columns={'estaciones': 'Estaciones_activas'}, inplace=True)

# 7. Crear gráfico Altair
chart = alt.Chart(expansion).mark_bar(color='#4A90E2').encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('Estaciones_activas:Q', title='Número de estaciones activas'),
    tooltip=['Año', 'Estaciones_activas']
).properties(
    title='Expansión nacional de la red de monitoreo (2000–2026)',
    width=700,
    height=400
)

# 8. Exportar en HTML interactivo
chart.save('expansion_nacional.html')

print("✅ Gráfico generado correctamente: expansion_nacional.html")

from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# --- Expansión nacional de la red (2000–2026) ---
# Script listo para Google Colab

import pandas as pd
import altair as alt

# 1. Cargar la base analítica (ya subida en Colab)
df = pd.read_excel('base_analitica_calidad_aire.xlsx')

# 2. Asegurar que 'valor' sea numérico
df['valor'] = pd.to_numeric(df['valor'], errors='coerce')

# 3. Filtrar solo filas con datos válidos
df_valid = df.dropna(subset=['valor'])

# 4. Detectar primer año con dato válido por estación
inicio = df_valid.groupby('estacion')['anio'].min().reset_index()
inicio.columns = ['estacion', 'anio_inicio']

# 5. Contar cuántas estaciones estaban activas cada año
años = pd.DataFrame({'anio': range(2000, 2027)})
años['estaciones_activas'] = años['anio'].apply(lambda a: (inicio['anio_inicio'] <= a).sum())

# 6. Crear gráfico Altair
chart = alt.Chart(años).mark_bar(color='#4A90E2').encode(
    x=alt.X('anio:O', title='Año'),
    y=alt.Y('estaciones_activas:Q', title='Número de estaciones activas'),
    tooltip=['anio', 'estaciones_activas']
).properties(
    title='Expansión nacional de la red de monitoreo (2000–2026)',
    width=700,
    height=400
)

# 7. Exportar en HTML interactivo
chart.save('expansion_nacional.html')

print("✅ Gráfico generado correctamente: expansion_nacional.html")

# --- Expansión de la red de monitoreo por región (2000–2026) ---
# Script final para Google Colab

import pandas as pd
import altair as alt

# 1. Cargar las bases
df1 = pd.read_excel('base_analitica_calidad_aire.xlsx')
df2 = pd.read_excel('BASE DE DATOS Cánepa.xlsx')

# 2. Unificar estructura y limpiar
df1['valor'] = pd.to_numeric(df1['valor'], errors='coerce')
df1 = df1.dropna(subset=['region', 'estacion', 'anio'])

# 3. Detectar primer año con dato válido por estación
inicio = df1.groupby(['region', 'estacion'])['anio'].min().reset_index()
inicio.columns = ['region', 'estacion', 'anio_inicio']

# 4. Crear tabla de expansión por región y año
años = pd.DataFrame({'anio': range(2000, 2027)})
expansion = []
for r in inicio['region'].unique():
    datos_r = inicio[inicio['region'] == r]
    años_r = años.copy()
    años_r['region'] = r
    años_r['estaciones_activas'] = años_r['anio'].apply(lambda a: (datos_r['anio_inicio'] <= a).sum())
    expansion.append(años_r)
df_expansion = pd.concat(expansion)

# 5. Crear gráfico Altair
chart = alt.Chart(df_expansion).mark_line(point=True).encode(
    x=alt.X('anio:O', title='Año'),
    y=alt.Y('estaciones_activas:Q', title='Número de estaciones activas'),
    color=alt.Color('region:N', title='Región'),
    tooltip=['region', 'anio', 'estaciones_activas']
).properties(
    title='Expansión de la red de monitoreo por región (2000–2026)',
    width=700,
    height=400
)

# 6. Exportar gráfico a HTML
chart.save('expansion_por_region.html')

print("✅ Gráfico generado correctamente: expansion_por_region.html")

# --- Expansión de la red de monitoreo por región (2000–2026) ---
import pandas as pd
import altair as alt
import glob

# 1. Cargar todos los CSV en una lista
archivos = [
    "antofagasta.csv",
    "atacama.csv",
    "bio bio2.csv",
    "coquimbo.csv",
    "la araucania.csv",
    "los rios.csv",
    "maule.csv",
    "nuble.csv",
    "ohiggins.csv",
    "RM1.csv",
    "valparaiso.csv"
]

# 2. Transformar cada CSV a formato largo (tidy)
dfs = []
for archivo in archivos:
    df = pd.read_csv(archivo, sep=";", decimal=",")
    # La primera columna es la estación o región
    df_long = df.melt(id_vars=[df.columns[0]],
                      var_name="anio",
                      value_name="valor")
    df_long["region"] = archivo.replace(".csv","")
    df_long.rename(columns={df.columns[0]:"estacion"}, inplace=True)
    dfs.append(df_long)

# 3. Concatenar todo
df_all = pd.concat(dfs, ignore_index=True)

# 4. Limpiar datos
df_all["anio"] = pd.to_numeric(df_all["anio"], errors="coerce")
df_all["valor"] = pd.to_numeric(df_all["valor"], errors="coerce")
df_all = df_all.dropna(subset=["anio"])

# 5. Detectar primer año con dato válido por estación
inicio = df_all.dropna(subset=["valor"]).groupby(["region","estacion"])["anio"].min().reset_index()
inicio.columns = ["region","estacion","anio_inicio"]

# 6. Construir tabla de expansión por región
años = pd.DataFrame({"anio": range(2000, 2027)})
expansion = []
for r in inicio["region"].unique():
    datos_r = inicio[inicio["region"] == r]
    años_r = años.copy()
    años_r["region"] = r
    años_r["estaciones_activas"] = años_r["anio"].apply(lambda a: (datos_r["anio_inicio"] <= a).sum())
    expansion.append(años_r)
df_expansion = pd.concat(expansion)

# 7. Gráfico Altair
chart = alt.Chart(df_expansion).mark_line(point=True).encode(
    x=alt.X("anio:O", title="Año"),
    y=alt.Y("estaciones_activas:Q", title="Número de estaciones activas"),
    color=alt.Color("region:N", title="Región"),
    tooltip=["region","anio","estaciones_activas"]
).properties(
    title="Expansión de la red de monitoreo por región (2000–2026)",
    width=700,
    height=400
)

# 8. Exportar a HTML
chart.save("expansion_por_region.html")
print("✅ Gráfico generado: expansion_por_region.html")