# -*- coding: utf-8 -*-
"""expansión regional

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cxBIUoTu_K5DURcesZ2xBXtnS8-oj31
"""

# --- Expansión de la red de monitoreo por región (2000–2026) ---
import pandas as pd
import altair as alt
import glob

# 1. Cargar todos los CSV en una lista
archivos = [
    "antofagasta.csv",
    "atacama.csv",
    "bio bio2.csv",
    "coquimbo.csv",
    "la araucania.csv",
    "los rios.csv",
    "maule.csv",
    "nuble.csv",
    "ohiggins.csv",
    "RM1.csv",
    "valparaiso.csv"
]

# 2. Transformar cada CSV a formato largo (tidy)
dfs = []
for archivo in archivos:
    df = pd.read_csv(archivo, sep=";", decimal=",")
    # La primera columna es la estación o región
    df_long = df.melt(id_vars=[df.columns[0]],
                      var_name="anio",
                      value_name="valor")
    df_long["region"] = archivo.replace(".csv","")
    df_long.rename(columns={df.columns[0]:"estacion"}, inplace=True)
    dfs.append(df_long)

# 3. Concatenar todo
df_all = pd.concat(dfs, ignore_index=True)

# 4. Limpiar datos
df_all["anio"] = pd.to_numeric(df_all["anio"], errors="coerce")
df_all["valor"] = pd.to_numeric(df_all["valor"], errors="coerce")
df_all = df_all.dropna(subset=["anio"])

# 5. Detectar primer año con dato válido por estación
inicio = df_all.dropna(subset=["valor"]).groupby(["region","estacion"])["anio"].min().reset_index()
inicio.columns = ["region","estacion","anio_inicio"]

# 6. Construir tabla de expansión por región
años = pd.DataFrame({"anio": range(2000, 2027)})
expansion = []
for r in inicio["region"].unique():
    datos_r = inicio[inicio["region"] == r]
    años_r = años.copy()
    años_r["region"] = r
    años_r["estaciones_activas"] = años_r["anio"].apply(lambda a: (datos_r["anio_inicio"] <= a).sum())
    expansion.append(años_r)
df_expansion = pd.concat(expansion)

# 7. Gráfico Altair
chart = alt.Chart(df_expansion).mark_line(point=True).encode(
    x=alt.X("anio:O", title="Año"),
    y=alt.Y("estaciones_activas:Q", title="Número de estaciones activas"),
    color=alt.Color("region:N", title="Región"),
    tooltip=["region","anio","estaciones_activas"]
).properties(
    title="Expansión de la red de monitoreo por región (2000–2026)",
    width=700,
    height=400
)

# 8. Exportar a HTML
chart.save("expansion_por_region.html")
print("✅ Gráfico generado: expansion_por_region.html")

# --- Comparación Centro vs Sur (2000–2026) ---
import pandas as pd
import altair as alt

# 1. Cargar la base
df = pd.read_csv('basecentrovssu.csv', sep=';', decimal='.')

# 2. Transformar a formato largo (tidy)
df_long = df.melt('Año', var_name='Región', value_name='PM25_promedio_anual')

# 3. Crear gráfico Altair
chart = alt.Chart(df_long).mark_line(point=True).encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('PM25_promedio_anual:Q', title='PM2.5 promedio anual (µg/m³)'),
    color=alt.Color('Región:N', title='Región',
                    scale=alt.Scale(domain=['Metropolitana', 'Temuco'],
                                    range=['#F5A623', '#4A90E2'])),
    tooltip=['Año', 'Región', 'PM25_promedio_anual']
).properties(
    title='Comparación Sur vs Centro (2000–2026)',
    width=700,
    height=400
)

# 4. Exportar a HTML
chart.save('grafico_centrovssur.html')
print("✅ Gráfico generado correctamente: grafico_centrovssur.html")

# --- Tendencias divergentes de PM2.5 por región (2000–2026) ---
import pandas as pd
import altair as alt

# 1. Crear la base directamente en el script
data = {
    "Año": list(range(2000, 2027)),
    "Araucania": [30,32,31,33,34,35,36,37,38,36,33,34,50.8,33,32,31,30,29,28,27,26,25,24,23,22,23,24],
    "Bio Bio": [28,29,30,31,32,33,34,35,36,37,38,37,36,35,34,33,32,31,30,29,28,27,26,25,26,27,28],
    "Metropolitana": [33,32,31,30,29,28,27,26,25,24,23,22,25,24,23,22,21,20,20,19,19,18,18,17,17,18,19]
}

df = pd.DataFrame(data)

# 2. Transformar a formato largo (tidy)
df_long = df.melt('Año', var_name='Región', value_name='PM25_promedio_anual')

# 3. Crear gráfico Altair
chart = alt.Chart(df_long).mark_line(point=True).encode(
    x=alt.X('Año:O', title='Año'),
    y=alt.Y('PM25_promedio_anual:Q', title='PM2.5 promedio anual (µg/m³)'),
    color=alt.Color('Región:N', title='Región',
                    scale=alt.Scale(domain=['Araucania', 'Bio Bio', 'Metropolitana'],
                                    range=['#4A90E2', '#F5A623', '#D0021B'])),
    tooltip=['Región', 'Año', 'PM25_promedio_anual']
).properties(
    title='Tendencias divergentes de PM2.5 por región (2000–2026)',
    width=700,
    height=400
)

# 4. Exportar a HTML
chart.save('grafico_tendencias_divergentes.html')
print("✅ Gráfico generado correctamente: grafico_tendencias_divergentes.html")